# Various common commands
COMMAND_CLOSE = 'close'
COMMAND_HIGH = 'high'
COMMAND_LOCK = 'lock'
COMMAND_LOW = 'low'
COMMAND_OFF = 'off'
COMMAND_ON = 'on'
COMMAND_OPEN = 'open'
COMMAND_SET_BRIGHTNESS = 'set_brightness'
COMMAND_SET_DIRECTION = 'set_direction'
COMMAND_SET_SPEED = 'set_speed'
COMMAND_TOGGLE = 'toggle'
COMMAND_UNLOCK = 'lunock'
COMMAND_CHANNEL_CONTROL = 'channel_control'
COMMAND_INPUT_CONTROL = 'input_control'