DASHBOARD_NAV = [
    {
        "parent": None,
        "label": "ui.navigation.dashboard",
        "icon": "fas fa-home",
        "path": "dashboard",
        "priority": 0,
    },
    {
        "parent": None,
        "label": "ui.navigation.devices",
        "icon": "fas fa-lightbulb",
        "path": "dashboard-devices",
        "priority": 1000,
    },
    {
        "parent": "ui.navigation.devices",
        "label": "ui.navigation.list",
        "path": {"name": "dashboard-devices", "params": {}},
        "priority": 1000,
    },
    {
        "parent": "ui.navigation.devices",
        "label": "ui.navigation.add",
        "path": {"name": "dashboard-devices-add", "params": {}},
        "priority": 2000,
    },
    {
        "parent": "ui.navigation.devices",
        "label": "ui.navigation.discovered",
        "path": {"name": "dashboard-discovered", "params": {}},
        "priority": 3000,
    },
    {
        "parent": "ui.navigation.devices",
        "label": "ui.navigation.device_commands",
        "path": {"name": "dashboard-device_commands", "params": {}},
        "priority": 4000,
    },
    {
        "parent": None,
        "label": "ui.navigation.automation",
        "icon": "fas fa-random",
        "path": "dashboard-automation",
        "priority": 2000,
    },
    {
        "parent": "ui.navigation.automation",
        "label": "ui.navigation.scenes",
        "path": {"name": "dashboard-scenes", "params": {}},
        "priority": 1000,
    },
    {
        "parent": "ui.navigation.automation",
        "label": "ui.navigation.crontab",
        "path": {"name": "dashboard-crontab", "params": {}},
        "priority": 2000,
    },
    # module configs - 3000
    {
        "parent": None,
        "label": "ui.navigation.info",
        "icon": "fas fa-info",
        "path": "dashboard-info",
        "priority": 4000,
    },
    {
        "parent": "ui.navigation.info",
        "label": "ui.navigation.atoms",
        "path": {"name": "dashboard-atoms", "params": {}},
        "priority": 1000,
    },
    {
        "parent": "ui.navigation.info",
        "label": "ui.navigation.intents",
        "path": {"name": "dashboard-intents", "params": {}},
        "priority": 2000,
    },
    {
        "parent": "ui.navigation.info",
        "label": "ui.navigation.states",
        "path": {"name": "dashboard-states", "params": {}},
        "priority": 3000,
    },
    {
        "parent": "ui.navigation.info",
        "label": "ui.navigation.storage",
        "path": {"name": "dashboard-storage", "params": {}},
        "priority": 4000,
    },
    # 4000 is reserved for the frontend navbar section. This can be found in:
    # yombo-gateway/yombo/lib/webinterface/mixins/frontend.py
    {
        "parent": None,
        "label": "ui.navigation.statistics",
        "icon": "fas fa-chart-bar",
        "path": "dashboard-statistics",
        "priority": 5000,
    },
    {
        "parent": None,
        "label": "ui.navigation.permissions",
        "icon": "fas fa-user-shield",
        "path": "dashboard-permissions",
        "priority": 6000,
    },
    {
        "parent": "ui.navigation.permissions",
        "label": "ui.navigation.authkeys",
        "path": {"name": "dashboard-authkeys", "params": {}},
        "priority": 1000,
    },
    {
        "parent": "ui.navigation.permissions",
        "label": "ui.navigation.roles",
        "path": {"name": "dashboard-roles", "params": {}},
        "priority": 2000,
    },
    {
        "parent": "ui.navigation.permissions",
        "label": "ui.navigation.users",
        "path": {"name": "dashboard-users", "params": {}},
        "priority": 3000,
    },
    {
        "parent": None,
        "label": "ui.navigation.user",
        "icon": "fas fa-user",
        "path": "dashboard-user",
        "priority": 7000,
    },
    {
        "parent": "ui.navigation.user",
        "label": "ui.navigation.gateways",
        "path": {"name": "dashboard-gateways", "params": {}},
        "priority": 1000,
    },
    {
        "parent": "ui.navigation.user",
        "label": "ui.navigation.locations",
        "path": {"name": "dashboard-locations", "params": {}},
        "priority": 2000,
    },
    {
        "parent": "ui.navigation.user",
        "label": "ui.navigation.areas",
        "path": {"name": "dashboard-areas", "params": {}},
        "priority": 3000,
    },
    {
        "parent": None,
        "label": "ui.navigation.system",
        "icon": "fas fa-cogs",
        "path": "dashboard-system",
        "priority": 8000,
    },
    {
        "parent": "ui.navigation.system",
        "label": "ui.navigation.overview",
        "path": {"name": "dashboard-system-overview", "params": {}},
        "priority": 1000,
    },
    {
        "parent": "ui.navigation.system",
        "label": "ui.navigation.modules",
        "path": {"name": "dashboard-gateway_modules", "params": {}},
        "priority": 2000,
    },
    {
        "parent": "ui.navigation.system",
        "label": "ui.navigation.configuration",
        "path": {"name": "dashboard-configuration", "params": {}},
        "priority": 3000,
    },
    {
        "parent": "ui.navigation.system",
        "label": "ui.navigation.backup",
        "path": {"name": "dashboard-system-backup", "params": {}},
        "priority": 4000,
    },
    {
        "parent": "ui.navigation.system",
        "label": "ui.navigation.dns",
        "path": {"name": "dashboard-dns", "params": {}},
        "priority": 5000,
    },
    {
        "parent": "ui.navigation.system",
        "label": "ui.navigation.encryption",
        "path": {"name": "dashboard-encryption", "params": {}},
        "priority": 6000,
    },
    {
        "parent": "ui.navigation.system",
        "label": "ui.navigation.webinterface_logs",
        "path": {"name": "dashboard-webinterface_logs", "params": {}},
        "priority": 7000,
    },
    {
        "parent": None,
        "label": "ui.navigation.mqtt",
        "icon": "fas fa-envelope",
        "path": "dashboard-mqtt",
        "priority": 9000,
    },
    {
        "parent": "ui.navigation.mqtt",
        "label": "ui.navigation.monitor",
        "path": {"name": "dashboard-mqtt-monitor", "params": {}},
        "priority": 1000,
    },
    {
        "parent": "ui.navigation.mqtt",
        "label": "ui.navigation.send",
        "path": {"name": "dashboard-mqtt", "params": {}},
        "priority": 2000,
    },
    {
        "parent": None,
        "label": "ui.navigation.debug",
        "icon": "fas fa-bug",
        "path": "dashboard-debug",
        "priority": 10000,
    },
    {
        "parent": "ui.navigation.debug",
        "label": "ui.navigation.atoms",
        "path": {"name": "dashboard-debug-generic-id", "params": {"id": "atoms"}},
        "priority": 2000,
    },
    {
        "parent": "ui.navigation.debug",
        "label": "ui.navigation.authentication_platforms",
        "path": {"name": "dashboard-debug-authentication_platforms", "params": {}},
        "priority": 3000,
    },
    {
        "parent": "ui.navigation.debug",
        "label": "ui.navigation.automation_rules",
        "path": {"name": "dashboard-debug-generic-id", "params": {"id": "automation_rules"}},
        "priority": 4000,
    },
    {
        "parent": "ui.navigation.debug",
        "label": "ui.navigation.cache",
        "path": {"name": "dashboard-debug-generic-id", "params": {"id": "cache"}},
        "priority": 5000,
    },
    {
        "parent": "ui.navigation.debug",
        "label": "ui.navigation.commands",
        "path": {"name": "dashboard-debug-generic-id", "params": {"id": "commands"}},
        "priority": 6000,
    },
    {
        "parent": "ui.navigation.debug",
        "label": "ui.navigation.devices",
        "path": {"name": "dashboard-debug-generic-id", "params": {"id": "devices"}},
        "priority": 7000,
    },
    {
        "parent": "ui.navigation.debug",
        "label": "ui.navigation.device_command_types",
        "path": {"name": "dashboard-debug-generic-id", "params": {"id": "device_command_types"}},
        "priority": 8000,
    },
    {
        "parent": "ui.navigation.debug",
        "label": "ui.navigation.device_types",
        "path": {"name": "dashboard-debug-generic-id", "params": {"id": "device_types"}},
        "priority": 9000,
    },
    {
        "parent": "ui.navigation.debug",
        "label": "ui.navigation.gateways",
        "path": {"name": "dashboard-debug-generic-id", "params": {"id": "gateways"}},
        "priority": 10000,
    },
    {
        "parent": "ui.navigation.debug",
        "label": "ui.navigation.hooks_called_libraries",
        "path": {"name": "dashboard-debug-hooks_called_libraries", "params": {}},
        "priority": 11000,
    },
    {
        "parent": "ui.navigation.debug",
        "label": "ui.navigation.hooks_called_modules",
        "path": {"name": "dashboard-debug-hooks_called_modules", "params": {}},
        "priority": 12000,
    },
    {
        "parent": "ui.navigation.debug",
        "label": "ui.navigation.http_event_stream",
        "path": {"name": "dashboard-debug-http_event_stream", "params": {}},
        "priority": 13000,
    },
    {
        "parent": "ui.navigation.debug",
        "label": "ui.navigation.input_types",
        "path": {"name": "dashboard-debug-generic-id", "params": {"id": "input_types"}},
        "priority": 14000,
    },
    {
        "parent": "ui.navigation.debug",
        "label": "ui.navigation.locations",
        "path": {"name": "dashboard-debug-generic-id", "params": {"id": "locations"}},
        "priority": 15000,
    },
    {
        "parent": "ui.navigation.debug",
        "label": "ui.navigation.module_device_types",
        "path": {"name": "dashboard-debug-generic-id", "params": {"id": "module_device_types"}},
        "priority": 16000,
    },
    {
        "parent": "ui.navigation.debug",
        "label": "ui.navigation.modules",
        "path": {"name": "dashboard-debug-generic-id", "params": {"id": "modules"}},
        "priority": 17000,
    },
    {
        "parent": "ui.navigation.debug",
        "label": "ui.navigation.notifications",
        "path": {"name": "dashboard-debug-generic-id", "params": {"id": "notifications"}},
        "priority": 18000,
    },
    {
        "parent": "ui.navigation.debug",
        "label": "ui.navigation.requirements",
        "path": {"name": "dashboard-debug-requirements", "params": {}},
        "priority": 19000,
    },
    {
        "parent": "ui.navigation.debug",
        "label": "ui.navigation.scenes",
        "path": {"name": "dashboard-debug-generic-id", "params": {"id": "scenes"}},
        "priority": 20000,
    },
    {
        "parent": "ui.navigation.debug",
        "label": "ui.navigation.sqldictionaries",
        "path": {"name": "dashboard-debug-generic-id", "params": {"id": "sqldicts"}},
        "priority": 21000,
    },
    {
        "parent": "ui.navigation.debug",
        "label": "ui.navigation.states",
        "path": {"name": "dashboard-debug-generic-id", "params": {"id": "states"}},
        "priority": 22000,
    },
    {
        "parent": "ui.navigation.debug",
        "label": "ui.navigation.statistic_bucket_lifetimes",
        "path": {"name": "dashboard-debug-statistic_bucket_lifetimes", "params": {}},
        "priority": 23000,
    },
    {
        "parent": "ui.navigation.debug",
        "label": "ui.navigation.states",
        "path": {"name": "dashboard-debug-generic-id", "params": {"id": "states"}},
        "priority": 24000,
    },
    {
        "parent": "ui.navigation.debug",
        "label": "ui.navigation.storage",
        "path": {"name": "dashboard-debug-generic-id", "params": {"id": "storage"}},
        "priority": 25000,
    },
    {
        "parent": "ui.navigation.debug",
        "label": "ui.navigation.users",
        "path": {"name": "dashboard-debug-generic-id", "params": {"id": "users"}},
        "priority": 26000,
    },
    {
        "parent": "ui.navigation.debug",
        "label": "ui.navigation.variable_data",
        "path": {"name": "dashboard-debug-generic-id", "params": {"id": "variable_data"}},
        "priority": 27000,
    },
    {
        "parent": "ui.navigation.debug",
        "label": "ui.navigation.variable_fields",
        "path": {"name": "dashboard-debug-generic-id", "params": {"id": "variable_fields"}},
        "priority": 28000,
    },
    {
        "parent": "ui.navigation.debug",
        "label": "ui.navigation.variable_groups",
        "path": {"name": "dashboard-debug-generic-id", "params": {"id": "variable_groups"}},
        "priority": 29000,
    },
    {
        "parent": None,
        "label": "ui.navigation.examples",
        "icon": "fas fa-laptop-code",
        "path": "dashboard-examples",
        "priority": 100000,
    },

]

GLOBAL_ITEMS_NAV = [
    {
        "parent": None,
        "label": "ui.navigation.global_items",
        "icon": "fas fa-home",
        "path": "global_items",
        "priority": 1000,
    },
    {
        "parent": None,
        "label": "ui.navigation.commands",
        "icon": "fas fa-terminal",
        "path": "global_items-commands",
        "priority": 10000,
    },
    {
        "parent": None,
        "label": "ui.navigation.device_types",
        "icon": "fas fa-lightbulb",
        "path": "global_items-device_types",
        "priority": 20000,
    },
    {
        "parent": None,
        "label": "ui.navigation.modules",
        "icon": "fas fa-puzzle-piece",
        "path": "global_items-modules",
        "priority": 40000,
    },
]
