TRUST_UNDEFINED = 0
TRUST_NEVER = 1
TRUST_MARGINAL = 2
TRUST_FULLY = 3
TRUST_ULTIMATE = 4

TRUST_LEVELS = {
    "TRUST_UNDEFINED": TRUST_UNDEFINED,
    "TRUST_NEVER": TRUST_NEVER,
    "TRUST_MARGINAL": TRUST_MARGINAL,
    "TRUST_FULLY": TRUST_FULLY,
    "TRUST_ULTIMATE": TRUST_ULTIMATE,
}

TRUST_MAP = {
    0: TRUST_UNDEFINED,
    1: TRUST_NEVER,
    2: TRUST_MARGINAL,
    3: TRUST_FULLY,
    4: TRUST_ULTIMATE,
}