from typing import Dict, Union

HARD_LOAD: Dict[str, Dict[str, Union[bool, str]]] = {
    "Tools": {"operating_mode": "all", "order": 1000},
    "Encryption": {"operating_mode": "all", "order": 1400},
    "Cache": {"operating_mode": "all", "order": 1800},
    "Nodes": {"operating_mode": "all", "order": 2200},
    "CallLater": {"operating_mode": "all", "order": 2600},
    "Configs": {"operating_mode": "all", "order": 3000},
    "Users": {"operating_mode": "all", "order": 3400},
    "Events": {"operating_mode": "all", "order": 3800},
    "Validate": {"operating_mode": "all", "order": 4200},
    "LocalDB": {"operating_mode": "all", "order": 4800},
    "Atoms": {"operating_mode": "all", "order": 5200},
    "States": {"operating_mode": "all", "order": 5600},
    "Requests": {"operating_mode": "all", "order": 6000},
    "YomboAPI": {"operating_mode": "all", "order": 6400},
    "Startup": {"operating_mode": "all", "order": 6800},
    "SQLDicts": {"operating_mode": "all", "order": 7200},
    "Files": {"operating_mode": "all", "order": 7600},
    "SystemDataHandler": {"operating_mode": "run", "order": 8000},
    "Categories": {"operating_mode": "all", "order": 8400},
    "Commands": {"operating_mode": "all", "order": 8800},
    "Locations": {"operating_mode": "all", "order": 9200},
    "Template": {"operating_mode": "all", "order": 9600},
    "Queue": {"operating_mode": "all", "order": 1000},
    "Notifications": {"operating_mode": "all", "order": 10400},
    "GPG": {"operating_mode": "run", "order": 10800},
    "Localize": {"operating_mode": "all", "order": 11200},
    "Hash": {"operating_mode": "all", "order": 11600},
    "HashIDS": {"operating_mode": "all", "order": 11200},
    "Discovery": {"operating_mode": "all", "order": 12400},
    "Statistics": {"operating_mode": "all", "order": 12800},  # TODO: Convert database to new format.
    "AMQP": {"operating_mode": "run", "order": 13200},
    "CronTab": {"operating_mode": "all", "order": 13600},
    "Times": {"operating_mode": "all", "order": 14000},
    "VariableData": {"operating_mode": "all", "order": 14400},
    "VariableFields": {"operating_mode": "all", "order": 14800},
    "VariableGroups": {"operating_mode": "all", "order": 15200},
    "DeviceCommandInputs": {"operating_mode": "all", "order": 15600},
    "DeviceTypeCommands": {"operating_mode": "all", "order": 16000},
    "Gateways": {"operating_mode": "all", "order": 16400},
    "AMQPYombo": {"operating_mode": "run", "order": 16800},
    "DownloadModules": {"operating_mode": "run", "order": 17200},
    "ModuleDeviceTypes": {"operating_mode": "all", "order": 17800},
    "Modules": {"operating_mode": "all", "order": 18200},
    "DeviceTypes": {"operating_mode": "all", "order": 18600},
    "InputTypes": {"operating_mode": "all", "order": 19000},
    "Devices": {"operating_mode": "all", "order": 19400},
    "DeviceStates": {"operating_mode": "all", "order": 19800},
    "DeviceCommands": {"operating_mode": "all", "order": 20200},
    "SSLCerts": {"operating_mode": "all", "order": 20600},
    "Mosquitto": {"operating_mode": "all", "order": 21000},
    "MQTTUsers": {"operating_mode": "run", "order": 21400},
    "MQTT": {"operating_mode": "run", "order": 21800},
    "MQTTYombo": {"operating_mode": "run", "order": 22200},
    "WebSessions": {"operating_mode": "all", "order": 22600},
    "WebInterface": {"operating_mode": "all", "order": 23000},
    "Tasks": {"operating_mode": "all", "order": 23400},
    "Scenes": {"operating_mode": "all", "order": 24200},
    "Roles": {"operating_mode": "all", "order": 24600},
    "Permissions": {"operating_mode": "all", "order": 25000},
    "AuthKeys": {"operating_mode": "all", "order": 25400},
    "Intents": {"operating_mode": "all", "order": 25800},
    "Storage": {"operating_mode": "all", "order": 26200},
}

HARD_UNLOAD = {
    "Encryption": {"operating_mode": "all", "order": 1000},
    "Modules": {"operating_mode": "all", "order": 1400},
    "Scenes": {"operating_mode": "all", "order": 2600},
    "MQTT": {"operating_mode": "run", "order": 3000},
    "Intents": {"operating_mode": "all", "order": 3400},
    # Below this line, doesn't matter the order.
    "Nodes": {"operating_mode": "all", "order": 3800},
    "CallLater": {"operating_mode": "all", "order": 4200},
    "Users": {"operating_mode": "all", "order": 4600},
    "Events": {"operating_mode": "all", "order": 5000},
    "Validate": {"operating_mode": "all", "order": 5400},
    "Atoms": {"operating_mode": "all", "order": 5800},
    "States": {"operating_mode": "all", "order": 6200},
    "Requests": {"operating_mode": "all", "order": 6800},
    "YomboAPI": {"operating_mode": "all", "order": 7200},
    "Startup": {"operating_mode": "all", "order": 7600},
    "SQLDicts": {"operating_mode": "all", "order": 8000},
    "Files": {"operating_mode": "all", "order": 8400},
    "Cache": {"operating_mode": "all", "order": 8800},
    "SystemDataHandler": {"operating_mode": "run", "order": 9200},
    "Categories": {"operating_mode": "all", "order": 9600},
    "Commands": {"operating_mode": "all", "order": 10000},
    "Locations": {"operating_mode": "all", "order": 10400},
    "Template": {"operating_mode": "all", "order": 10800},
    "Queue": {"operating_mode": "all", "order": 11200},
    "Notifications": {"operating_mode": "all", "order": 11600},
    "GPG": {"operating_mode": "run", "order": 12000},
    "Localize": {"operating_mode": "all", "order": 12400},
    "Hash": {"operating_mode": "all", "order": 12800},
    "HashIDS": {"operating_mode": "all", "order": 13200},
    "Discovery": {"operating_mode": "all", "order": 13600},
    "Statistics": {"operating_mode": "all", "order": 14000},
    "AMQP": {"operating_mode": "run", "order": 14400},
    "CronTab": {"operating_mode": "all", "order": 14800},
    "Times": {"operating_mode": "all", "order": 15200},
    "VariableData": {"operating_mode": "all", "order": 15600},
    "VariableFields": {"operating_mode": "all", "order": 16000},
    "VariableGroups": {"operating_mode": "all", "order": 16400},
    "DeviceCommandInputs": {"operating_mode": "all", "order": 16800},
    "DeviceTypeCommands": {"operating_mode": "all", "order": 17200},
    "Gateways": {"operating_mode": "all", "order": 17600},
    "AMQPYombo": {"operating_mode": "run", "order": 18000},
    "DownloadModules": {"operating_mode": "run", "order": 18400},
    "ModuleDeviceTypes": {"operating_mode": "all", "order": 18800},
    "DeviceTypes": {"operating_mode": "all", "order": 19200},
    "InputTypes": {"operating_mode": "all", "order": 19600},
    "Devices": {"operating_mode": "all", "order": 20000},
    "DeviceStates": {"operating_mode": "all", "order": 20400},
    "DeviceCommands": {"operating_mode": "all", "order": 20800},
    "Mosquitto": {"operating_mode": "all", "order": 212000},
    "MQTTUsers": {"operating_mode": "run", "order": 21600},
    "MQTTYombo": {"operating_mode": "run", "order": 22000},
    "SSLCerts": {"operating_mode": "all", "order": 22400},
    "WebSessions": {"operating_mode": "all", "order": 22800},
    "WebInterface": {"operating_mode": "all", "order": 23200},
    "Tasks": {"operating_mode": "all", "order": 23600},
    "Roles": {"operating_mode": "all", "order": 24000},
    "Permissions": {"operating_mode": "all", "order": 24400},
    "AuthKeys": {"operating_mode": "all", "order": 24800},
    "Storage": {"operating_mode": "all", "order": 25200},
    # Above this line, doesn't matter the order.
    "Configs": {"operating_mode": "all", "order": 25600},
    "LocalDB": {"operating_mode": "all", "order": 26000},
    "Tools": {"operating_mode": "all", "order": 26400},
}


RUN_PHASE = {
    "system_init": 0,
    "system_start": 10,
    "libraries_import": 500,
    "libraries_init": 1000,
    "modules_import": 1500,
    "modules_pre_init": 2000,
    "modules_init": 2500,
    "libraries_load": 3000,
    "libraries_start": 3500,
    "libraries_started": 4000,
    "modules_preload": 4500,
    "modules_load": 5000,
    "modules_prestart": 5500,
    "modules_start": 6000,
    "modules_started": 6500,
    "system_loaded": 7000,
    "gateway_running": 10000,
    "shutdown": 15000,
    "modules_stop": 15500,
    "modules_unload": 16000,
    "libraries_stop": 16500,
    "libraries_unload": 17000,
}
