#!/usr/bin/env bash
#
#
# This script is called by yombo_update.  Please start this script from there.
#
#
#
#
#
#
#
#
#
#
#
# Handles updates for Ubuntu.
#
#
#

if [ "$USER" = "root" ] && [ "$SUDO_USER" == "" ]; then
  echo "This script cannot be run as root directly and must be run"
  echo "as the user owning the Yombo gateway service."
  echo ""
  echo "Logout as root and then:"
  echo "sudo ./debian_update"
  exit
fi

if [ "$(id -u)" -ne 0 ]; then
  echo "This script must run with sudo to gain root access. This"
  echo "is needed to install the latest updates. Run this the user"
  echo "owning the Yombo gateway service:"
  echo ""
  echo "sudo ./debian_update"
  echo ""
  exit
fi

YOMBO_SCRIPT_HELPER_DIR="$( cd "$(dirname "$0")" ; pwd -P )"
YOMBO_SCRIPT_DIR="$(dirname $YOMBO_SCRIPT_HELPER_DIR)"
YOMBO_ROOT_DIR="$(dirname $YOMBO_SCRIPT_DIR)"

LOGFILE=$HOME/yombo_update.log
LOGFILEDETAILED=$HOME/yombo_update_detailed.log

touch $LOGFILE
chown $SUDO_USER:$SUDO_USER $LOGFILE

touch
chown $SUDO_USER:$SUDO_USER $LOGFILEDETAILED

echo ""
echo "The log file for these changes will be available at: $LOGFILE";
echo "Detailed logs can be found: $LOGFILEDETAILED";
echo ""
echo "You can monitor the details log from another terminal: tail -f $LOGFILEDETAILED"
echo ""
function logsetup {
#    TMP=$(tail -n $RETAIN_NUM_LINES $LOGFILE 2>/dev/null) && echo "${TMP}" > $LOGFILE
    exec > >(tee -a $LOGFILE $LOGFILEDETAILED)
    exec 2>&1
}

function log {
    echo "[$(date --rfc-3339=seconds)]: $*"
}
logsetup

log "==> apt-get - Running update"
apt-get update >> $LOGFILEDETAILED 2>&1

log "==> apt-get - Running upgrade, downloading packages."
sudo apt-mark hold keyboard-configuration >> $LOGFILEDETAILED 2>&1
sudo apt-mark hold grub-pc >> $LOGFILEDETAILED 2>&1
apt-get upgrade --download-only -y >> $LOGFILEDETAILED 2>&1

log "==> apt-get - Running upgrade, installing packages."
apt-get upgrade -y >> $LOGFILEDETAILED 2>&1

sudo apt-mark unhold keyboard-configuration >> $LOGFILEDETAILED 2>&1
sudo apt-mark unhold grub-pc >> $LOGFILEDETAILED 2>&1

log "==> Updating global pip3"
sudo pip3 install --upgrade pip >> $LOGFILEDETAILED 2>&1

log "==> Updating global yarn modules"
sudo yarn upgrade >> $LOGFILEDETAILED 2>&1
