#!/usr/bin/env bash
set -e

if [ "$(id -u)" -eq 0 ]; then
    echo ""
    echo "This must NOT be run as root, instead run as the user running the Yombo Gateway"
    echo ""
    echo "If you created a dedicate account for this software, first log into that account."
    echo "Then run this script as:"
    echo ""
    echo "mycomputer> bash ./pyenv_install"
    echo ""
    exit
fi

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
PARENTPATH="$(dirname "$SCRIPTPATH")"
YOMBOPATH="$(dirname "$PARENTPATH")"

LOGFILE=/home/$USER/yombo_setup.log
LOGFILEDETAILED=/home/$USER/yombo_setup_detailed.log
function logsetup {
    exec > >(tee -a $LOGFILE $LOGFILEDETAILED)
    exec 2>&1
}

function log {
    echo "[$(date --rfc-3339=seconds)]: $*"
}
logsetup

log "==> Yombo Gateway installer: User level installer starting."

log "==> Installing pyenv"

if [ "$PYENV_ROOT" == "" ]; then
  log "==> pyenv not detected, or wasn't setup properly. Installing."
  cd
  curl -L https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer | bash >> $LOGFILEDETAILED 2>&1
  echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
  echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
  echo 'eval "$(pyenv init -)"' >> ~/.bashrc
  export PYENV_ROOT="$HOME/.pyenv"
  export PATH="$PYENV_ROOT/bin:$PATH"
  eval "$(pyenv init -)"
else
  log "==> pyenv is detected. Making sure it's up to date."
  cd /home/$USER/.pyenv && git pull >> $LOGFILEDETAILED 2>&1
fi

echo "Changing to: $YOMBOPATH"
cd $YOMBOPATH

log "==> Installing latest python 3.7.x series. This will take a few minutes."
log "==> Raspberry PI installs can take a very long time, we suggest making lunch.."

CORECOUNT=$(grep -c ^processor /proc/cpuinfo)
CORECOUNT=$(($CORECOUNT + 1))

log "==> Compiling python with '$CORECOUNT' core(s)."
#PYTHON_CONFIGURE_OPTS="--enable-optimizations" MAKE_OPTS="-j$CORECOUNT" pyenv install 3.7.3 -s
MAKE_OPTS="-j$CORECOUNT" pyenv install 3.7.3 -s
pyenv local 3.7.3

log "==> Updating pyenv pip3."
pip3 install --upgrade pip >> $LOGFILEDETAILED 2>&1

log "==> Updating / Installing python libraries."
pip3 install -r requirements.txt >> $LOGFILEDETAILED 2>&1

log "==> Done with yombo user based setup"
