#!/usr/bin/env bash
if [ "$EUID" -eq 0 ]; then
    echo ""
    echo "This must NOT be run as root, instead run as the user running the Yombo Gateway"
    echo ""
    echo "If you created a dedicate account for this software, first log into that account."
    echo "Then run this script as:"
    echo ""
    echo "mycomputer> bash ./pyenv-install.sh"
    echo ""
    exit
fi

YOMBO_SCRIPT_HELPER_DIR="$( cd "$(dirname "$0")" ; pwd -P )"
YOMBO_SCRIPT_DIR="$(dirname $YOMBO_SCRIPT_HELPER_DIR)"
YOMBO_ROOT_DIR="$(dirname $YOMBO_SCRIPT_DIR)"

cd /home/$USER/.pyenv && git pull

cd "$YOMBO_ROOT_DIR"

pip3 install --upgrade pip

CORECOUNT=$(grep -c ^processor /proc/cpuinfo)
CORECOUNT=$(($CORECOUNT + 1))

MAKE_OPTS="-j$CORECOUNT" pyenv install 3.7.3 -s

git pull
pip3 install --upgrade -r requirements.txt
