#!/usr/bin/env bash
#
#
# This script is called by yombo_update.  Please start this script from there.
#
#
#
#
#
#
#
#
#
#
#
# Handles updates for Ubuntu.
#
#
#

if [ "$USER" = "root" ] && [ "$SUDO_USER" == "" ]; then
  echo "This script cannot be run as root directly and must be run"
  echo "as the user owning the Yombo gateway service."
  echo ""
  echo "Logout as root and then:"
  echo "sudo yombo_update"
  exit
fi

if [ "$(id -u)" -ne 0 ]; then
  echo "This script must run with sudo to gain root access. This"
  echo "is needed to install the latest updates. Run this the user"
  echo "owning the Yombo gateway service:"
  echo ""
  echo "sudo yombo_update"
  echo ""
  exit
fi

YOMBO_SCRIPT_HELPER_DIR="$( cd "$(dirname "$0")" ; pwd -P )"
YOMBO_SCRIPT_DIR="$(dirname $YOMBO_SCRIPT_HELPER_DIR)"
YOMBO_ROOT_DIR="$(dirname $YOMBO_SCRIPT_DIR)"

touch /home/$SUDO_USER/yombo_setup.log
chown $SUDO_USER:$SUDO_USER /home/$SUDO_USER/yombo_setup.log

touch /home/$SUDO_USER/yombo_setup_detailed.log
chown $SUDO_USER:$SUDO_USER /home/$SUDO_USER/yombo_setup_detailed.log

LOGFILE=/home/$SUDO_USER/yombo_setup.log
LOGFILEDETAILED=/home/$SUDO_USER/yombo_setup_detailed.log
echo ""
echo "The log file for these changes will be available at: $LOGFILE";
echo "Detailed logs can be found: $LOGFILEDETAILED";
echo ""
echo "You can monitor the details log from another terminal: tail -f $LOGFILEDETAILED"
echo ""
function logsetup {
#    TMP=$(tail -n $RETAIN_NUM_LINES $LOGFILE 2>/dev/null) && echo "${TMP}" > $LOGFILE
    exec > >(tee -a $LOGFILE $LOGFILEDETAILED)
    exec 2>&1
}

function log {
    echo "[$(date --rfc-3339=seconds)]: $*"
}
logsetup

log "==> Running apt-get update"

apt-get update >> $LOGFILEDETAILED 2>&1

log "==> Running apt-get upgrade"
sudo apt-mark hold keyboard-configuration >> $LOGFILEDETAILED 2>&1
sudo apt-mark hold grub-pc >> $LOGFILEDETAILED 2>&1
apt-get upgrade -y >> $LOGFILEDETAILED 2>&1
sudo apt-mark unhold keyboard-configuration >> $LOGFILEDETAILED 2>&1
sudo apt-mark hold grub-pc >> $LOGFILEDETAILED 2>&1

log "==> Updating npm and pip3"
sudo npm update >> $LOGFILEDETAILED 2>&1

sudo pip3 install --upgrade pip >> $LOGFILEDETAILED 2>&1

log "==> Checking Mosquitto and its dependencies"
cd /usr/local/src/yombo/libwebsockets
git remote update >> $LOGFILEDETAILED 2>&1
UPSTREAM=${1:-'@{u}'}
LOCAL=$(git rev-parse @)
REMOTE=$(git rev-parse "$UPSTREAM")
BASE=$(git merge-base @ "$UPSTREAM")

if [ $LOCAL = $REMOTE ]; then
    LIBWEBSOCKETSUPDATED=no
    log "==> libsockets is current, skipping."
elif [ $LOCAL = $BASE ]; then
    log "==> libwebsockets is behind, updating.."
echo ""
    LIBWEBSOCKETSUPDATED=yes
    git pull >> $LOGFILEDETAILED 2>&1
    cd build
    make clean >> $LOGFILEDETAILED 2>&1
    cmake .. >> $LOGFILEDETAILED 2>&1
    sudo make install >> $LOGFILEDETAILED 2>&1
    sudo ldconfig >> $LOGFILEDETAILED 2>&1
fi

cd /usr/local/src/yombo/mosquitto-auth-plug
git remote update >> $LOGFILEDETAILED 2>&1
UPSTREAM=${1:-'@{u}'}
LOCAL=$(git rev-parse @)
REMOTE=$(git rev-parse "$UPSTREAM")
BASE=$(git merge-base @ "$UPSTREAM")

if [ $LOCAL = $REMOTE ]; then
    log "==> Mosquitto auth plugin is current, updating.."
elif [ $LOCAL = $BASE ]; then
    log "==> Mosquitto auth plugin is behind, updating.."
    git pull >> $LOGFILEDETAILED 2>&1
    make clean >> $LOGFILEDETAILED 2>&1
    make >> $LOGFILEDETAILED 2>&1
fi

cd /usr/local/src/yombo/mosquitto
git remote update >> $LOGFILEDETAILED 2>&1
UPSTREAM=${1:-'@{u}'}
LOCAL=$(git rev-parse @)
REMOTE=$(git rev-parse "$UPSTREAM")
BASE=$(git merge-base @ "$UPSTREAM")

if [ $LOCAL = $REMOTE ] && [ $LIBWEBSOCKETSUPDATED = "no" ]; then
    log "==> Mosquitto, and it's dependants are current, skipping."
elif [ $LOCAL = $BASE ] || [ $LIBWEBSOCKETSUPDATED = "yes" ]; then
    log "==> Mosquitto is behind, or one of it's dependants were, updating mosquitto.."
    git pull >> $LOGFILEDETAILED 2>&1
    make clean >> $LOGFILEDETAILED 2>&1
    make binary WITH_WEBSOCKETS=yes WITH_DOCS=no CFLAGS=-I/usr/local/include/ >> $LOGFILEDETAILED 2>&1
    sudo make install WITH_WEBSOCKETS=yes WITH_DOCS=no CFLAGS=-I/usr/local/include/ >> $LOGFILEDETAILED 2>&1
fi
