# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'concurrent'

$systemCPU = Concurrent.physical_processor_count
if $systemCPU >= 6
  $systemCPU = 6
elsif $systemCPU < 1
  $systemCPU = 1
end

Vagrant.configure(2) do |config|
  config.vm.box = "generic/ubuntu1904"
  config.vm.synced_folder "../../", "/yombo-gateway"
  config.vm.synced_folder "./working_dir", "/home/vagrant/.yombo"
  config.vm.network "public_network"
  config.vm.network "forwarded_port", guest: 8123, host: 8123
  config.vm.network "forwarded_port", guest: 8080, host: 18080
  config.vm.network "forwarded_port", guest: 8443, host: 18443
  config.vm.provision "fix-no-tty", type: "shell" do |shell|
    shell.path = "provision.sh"
  end
# config.vm.provision "fix-no-tty", type: "shell", inline: $script
  config.vm.provider :virtualbox do |vb|
    vb.name = "yombo_gateway1904"
    vb.cpus = $systemCPU
    vb.customize ["modifyvm", :id, "--vram", "16"]
    vb.customize ['modifyvm', :id, "--memory", "1024"]
    vb.customize ["modifyvm", :id, "--usb", "on"]
    vb.customize ["modifyvm", :id, "--usbehci", "on"]
  end
  config.vm.provider :hyperv do |h, override|
    override.vm.box = "generic/ubuntu1904"
    override.vm.hostname = "contrib-ubuntu1904"
    h.vmname = "yombo_gateway1904"
    h.cpus = $systemCPU
    h.memory = 1024
    h.maxmemory = 1024
  end
end