# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'concurrent'

$systemCPU = Concurrent.physical_processor_count
if $systemCPU >= 6
  $systemCPU = 6
elsif $systemCPU < 1
  $systemCPU = 1
end

$systemRAMraw = `awk '/^MemTotal:/{print $2}' /proc/meminfo`
$systemRAM = $systemRAMraw.to_i
if $systemRAM < 8153292
  $useableRAM = "1024"
elseif $systemRAM = 8153292
  $useableRAM = "2048"
else
  $useableRAM = "4096"
end

Vagrant.configure(2) do |config|
  config.vm.boot_timeout = 900
  config.vm.box = "generic/ubuntu2004"
  config.vm.synced_folder "../../", "/yombo-gateway"
  config.vm.synced_folder "./working_dir", "/home/vagrant/.yombo"
  config.vm.network "public_network"
#  config.vm.network "forwarded_port", guest: 3000, host: 3000
  config.vm.network "forwarded_port", guest: 8123, host: 8123
  config.vm.network "forwarded_port", guest: 8080, host: 18080
  config.vm.network "forwarded_port", guest: 8443, host: 18443
  config.vm.provision "fix-no-tty", type: "shell" do |shell|
    shell.path = "provision.sh"
  end
# config.vm.provision "fix-no-tty", type: "shell", inline: $script
  config.vm.provider "virtualbox" do |vb|
    vb.name = "yombo_gateway2004"
    vb.cpus = $systemCPU
    vb.memory = $useableRAM
    vb.customize ["modifyvm", :id, "--vram", "16"]
    vb.customize ["modifyvm", :id, "--usb", "on"]
    vb.customize ["modifyvm", :id, "--usbehci", "on"]
  end
  config.vm.provider "hyperv" do |h, override|
    override.vm.box = "generic/ubuntu2004"
    override.vm.hostname = "contrib-ubuntu2004"
    h.vmname = "yombo_gateway2004"
    h.cpus = $systemCPU
    h.memory = $useableRAM
    h.maxmemory = $useableRAM
  end
end