#! /bin/sh

# Author: Mitch Schwenk
# Contact: https://yombo.net
# Version: 0.9.0

### BEGIN INIT INFO
# Provides:          yombo
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Should-Start:      $NetworkManager
# Should-Stop:       $NetworkManager
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts and stops yombo gateway
# Description:       Yombo Gateway is for automation of various devices around the home or office.
#            For more information see:  https://yombo.net
### END INIT INFO

#Required -- What user yombo runs as.
USER=SOURCE__USER #Set Linux/Unix user name here.

DAEMON=SOURCE__DAEMON
SERVICE_NAME=yombo
SERVICE_DIR=SOURCE__DIRECTORY
PIDFILE=/var/run/yombo/yombo.pid
LOGFILE=/var/log/yombo/yombo.log
DAEMON_OPTS="-p $PIDFILE -l $LOGFILE -L -t $SERVICE_DIR/yombo.tac"

# Set python path so twistd can find the plugin
export PYTHONPATH=$SERVICE_DIR

if [ ! -x $DAEMON ]; then
  echo "ERROR: Can't execute $DAEMON."
  exit 1
fi

if [ ! -d $SERVICE_DIR ]; then
  echo "ERROR: Directory doesn't exist: $SERVICE_DIR"
  exit 1
fi

start_service() {
  echo -n " * Starting $SERVICE_NAME... "
  start-stop-daemon -c $USER:$USER -Sq -p $PIDFILE -d $SERVICE_DIR -x $DAEMON -- $DAEMON_OPTS
  e=$?
  if [ $e -eq 1 ]; then
    echo "already running"
    return
  fi

  if [ $e -eq 255 ]; then
    echo "couldn't start :("
    return
  fi

  echo "done"
}

stop_service() {
  echo -n " * Stopping $SERVICE_NAME... "
  start-stop-daemon -Kq -R 10 -p $PIDFILE
  e=$?
  if [ $e -eq 1 ]; then
    echo "not running"
    return
  fi

  echo "done"
}

case "$1" in
  start)
    start_service
    ;;
  stop)
    stop_service
    ;;
  restart)
    stop_service
    start_service
    ;;
  *)
    echo "Usage: /etc/init.d/$SERVICE_NAME {start|stop|restart}" >&2
    exit 1   
    ;;
esac

exit 0
