#!/usr/bin/env bash
if [ "$EUID" -eq 0 ]; then
    echo ""
    echo "This must NOT be run as root, instead run as the user running the Yombo Gateway"
    echo ""
    echo "If you created a dedicate account for this software, first log into that account."
    echo "Then run this script as:"
    echo ""
    echo "mycomputer> bash ./pyenv-install.sh"
    echo ""
    exit
fi

echo "USER:   ################  $USER"

OPTIMIZE=$1

if [ "$OPTIMIZE" == "" ]; then
  echo "This script shouldn't be called directly. Use yombo_update script."
fi

if [ "$OPTIMIZE" == 'yes' ]; then
  # This can't be used on raspberry pi
  CFLAGS='-O2'
fi
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
cd "$SCRIPTPATH"

pip3 install --upgrade pip3
pip2 install --upgrade pip2
pip3 install netifaces

cd /home/$USER/.pyenv && git pull && cd -
cd /opt/yombo-gateway
git pull

pyenv install 3.6.5 -s
pyenv local 3.6.5

pip3 list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 pip3 install -U
pip3 install -r requirements.txt
