#!/usr/bin/env bash
if [ "$EUID" -eq 0 ]; then
    echo ""
    echo "This must NOT be run as root, instead run as the user running the Yombo Gateway"
    echo ""
    echo "If you created a dedicate account for this software, first log into that account."
    echo "Then run this script as:"
    echo ""
    echo "mycomputer> bash ./pyenv-install.sh"
    echo ""
    exit
fi

OPTIMIZE=$1

YOMBO_SCRIPT_DIR="$( cd "$(dirname "$0")" ; pwd -P )"
YOMBO_ROOT_DIR="$(dirname $YOMBO_SCRIPT_DIR)"

cd /home/$USER/.pyenv && git pull && cd -

cd "$YOMBO_ROOT_DIR"

pip3 install --upgrade pip
pip2 install --upgrade pip
pip3 install netifaces
#PYTHON_CONFIGURE_OPTS="--enable-optimizations" MAKE_OPTS="-j4" pyenv install 3.6.8 -s
MAKE_OPTS="-j4" pyenv install 3.6.8 -s
pyenv local 3.6.8

git pull
pip3 install --upgrade -r requirements.txt


