#!/usr/bin/env bash

if [ "$USER" = "root" ] && [ "$SUDO_USER" == "" ]; then
  echo "This script cannot be run as root directly and must be run"
  echo "as the user owning the Yombo gateway service."
  echo ""
  echo "Logout as root and then:"
  echo "sudo yombo_update"
  exit
fi

if [ "$(id -u)" -ne 0 ]; then
  echo "This script must run with sudo to gain root access. This"
  echo "is needed to install the latest updates. Run this the user"
  echo "owning the Yombo gateway service:"
  echo ""
  echo "sudo yombo_update"
  echo ""
  exit
fi

#YOMBO_SCRIPT_DIR="$( cd "$(dirname "$0")" ; pwd -P )"


YOMBO_SCRIPT_DIR="$( cd "$(dirname "$0")" ; pwd -P )"
YOMBO_ROOT_DIR="$(dirname $YOMBO_SCRIPT_DIR)"
cd "$YOMBO_SCRIPT_DIR"

usage()
{
cat << EOF
usage: $0 options

This script is a wrapper around various platform updaters.

OPTIONS:
   -x  Force x86_64 based system (Intel/AMD)
   -a  Force arm based system (Raspberry PI, etc)
EOF
}

# Determine OS platform
if [ -f /etc/os-release ]; then
    # freedesktop.org and systemd
    . /etc/os-release
    OS=$NAME
    VER=$VERSION_ID
elif type lsb_release >/dev/null 2>&1; then
    # linuxbase.org
    OS=$(lsb_release -si)
    VER=$(lsb_release -sr)
elif [ -f /etc/lsb-release ]; then
    # For some versions of Debian/Ubuntu without lsb_release command
    . /etc/lsb-release
    OS=$DISTRIB_ID
    VER=$DISTRIB_RELEASE
elif [ -f /etc/debian_version ]; then
    # Older Debian/Ubuntu/etc.
    OS=Debian
    VER=$(cat /etc/debian_version)
elif [[ "$OSTYPE" == "darwin"* ]]; then
    echo "Yombo isn't support on Mac OSX. You should use Vagrant:"
    echo "https://yombo.net/docs/gateway/vagrant"
    exit
elif [[ "$OSTYPE" == "cygwin" ]]; then
    # POSIX compatibility layer and Linux environment emulation for Windows
    echo "Yombo isn't support on Windows. You should use Vagrant:"
    echo "https://yombo.net/docs/gateway/vagrant"
    exit
elif [[ "$OSTYPE" == "msys" ]]; then
    # Lightweight shell and GNU utilities compiled for Windows (part of MinGW)
    echo "Yombo isn't support on Windows. You should use Vagrant:"
    echo "https://yombo.net/docs/gateway/vagrant"
    exit
elif [[ "$OSTYPE" == "win32" ]]; then
    echo "Yombo isn't support on Windows. You should use Vagrant:"
    echo "https://yombo.net/docs/gateway/vagrant"
    exit
elif [[ "$OSTYPE" == "freebsd"* ]]; then
    echo "This script hasn't been updated to support freebsd."
    echo "Feel free update and make a pull request"
    exit
else
    echo "Your operating system is unknown: $OSTYPE"
    echo "Please email us at support@yombo.net with the output of this script."
    exit
fi

echo "Detected: $OS -> $VER"

if [[ "$OS" == "Debian" ]]; then
    $YOMBO_SCRIPT_DIR/helpers/debian_update
    sudo runuser -l $SUDO_USER -c "bash -i $YOMBO_SCRIPT_DIR/helpers/debian_update_user"
elif [[ "$OS" == "Ubuntu" ]]; then
    $YOMBO_SCRIPT_DIR/helpers/ubuntu_update
    sudo runuser -l $SUDO_USER -c "bash -i $YOMBO_SCRIPT_DIR/helpers/ubuntu_update_user"
fi
